title: Bowen Niu
logo: /assets/Self_Photo.jpg
description: I am pursing MS degree in Computer Science at Northeastern University. I am also a sales representative.
show_downloads: true
theme: jekyll-theme-minimal

social_links:
  resume: /assets/Resume.pdf
  linkedin: "https://www.linkedin.com/in/bowen-niu-347152162/"
  gitHub: "https://github.com/Bowenniu"